 CLASS zcl_test_cds_travel_sb1 DEFINITION
  PUBLIC FINAL
  CREATE PUBLIC
  FOR TESTING.

   PUBLIC SECTION.
   PROTECTED SECTION.
   PRIVATE SECTION.
ENDCLASS.



CLASS ZCL_TEST_CDS_TRAVEL_SB1 IMPLEMENTATION.
ENDCLASS.
